/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard.index": [],
    "libraries.index": [],
    "libraries.create": [],
    "libraries.store": [],
    "libraries.edit": [
        {
            "name": "library",
            "required": true,
            "binding": "id"
        }
    ],
    "libraries.update": [
        {
            "name": "library",
            "required": true,
            "binding": "id"
        }
    ],
    "libraries.destroy": [
        {
            "name": "library",
            "required": true,
            "binding": "id"
        }
    ],
    "library.redirect": [],
    "library.select": [],
    "library.tracks.index": [],
    "library.tracks.show": [
        {
            "name": "track",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.playlists.index": [],
    "library.playlists.show": [
        {
            "name": "playlist",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.artists.index": [],
    "library.artists.show": [
        {
            "name": "artist",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.albums.index": [],
    "library.albums.show": [
        {
            "name": "album",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.genres.index": [],
    "library.genres.show": [
        {
            "name": "genre",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.labels.index": [],
    "library.labels.show": [
        {
            "name": "label",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.tracks.index": [
        {
            "name": "library",
            "required": true,
            "binding": "id"
        }
    ],
    "library.named.tracks.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "track",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.playlists.index": [
        {
            "name": "library",
            "required": true
        }
    ],
    "library.named.playlists.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "playlist",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.artists.index": [
        {
            "name": "library",
            "required": true
        }
    ],
    "library.named.artists.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "artist",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.albums.index": [
        {
            "name": "library",
            "required": true
        }
    ],
    "library.named.albums.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "album",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.genres.index": [
        {
            "name": "library",
            "required": true
        }
    ],
    "library.named.genres.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "genre",
            "required": true,
            "binding": "ID"
        }
    ],
    "library.named.labels.index": [
        {
            "name": "library",
            "required": true
        }
    ],
    "library.named.labels.show": [
        {
            "name": "library",
            "required": true
        },
        {
            "name": "label",
            "required": true,
            "binding": "ID"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
